import type { ProjectmanOperationArgument } from './types.js'

export type ProjectmanOperationCatalogRow = {
  toolId: string
  operationId: string
  summary: string
  args: readonly ProjectmanOperationArgument[]
}

const optional = (name: string): ProjectmanOperationArgument => ({ name, optional: true })
const required = (name: string): ProjectmanOperationArgument => ({ name, optional: false })
const sourceTimestampArgs = [optional('sourceCreatedAt'), optional('sourceUpdatedAt')]

export const PROJECTMAN_OPERATION_CATALOG_ROWS: ProjectmanOperationCatalogRow[] = [
  {
    toolId: 'projectman-kanban-board-list',
    operationId: 'kanban-board.list',
    summary: 'List kanban boards by filters.',
    args: [optional('scopeId'), optional('project'), optional('name'), optional('includeArchived')],
  },
  {
    toolId: 'projectman-kanban-board-get',
    operationId: 'kanban-board.get',
    summary: 'Get a kanban board record by id.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-kanban-board-bootstrap',
    operationId: 'kanban-board.bootstrap',
    summary: 'Create a kanban board with default columns (Backlog/Todo/Doing/Done) and board-column links in one explicit op.',
    args: [optional('scopeId'), optional('project'), required('name'), optional('description'), optional('slug'), optional('position'), optional('columns'), ...sourceTimestampArgs],
  },
  {
    toolId: 'projectman-kanban-board-create',
    operationId: 'kanban-board.create',
    summary: 'Create a kanban board.',
    args: [optional('scopeId'), optional('project'), required('name'), optional('description'), optional('slug'), optional('position'), ...sourceTimestampArgs],
  },
  {
    toolId: 'projectman-kanban-board-update',
    operationId: 'kanban-board.update',
    summary: 'Patch a kanban board by id.',
    args: [required('id'), optional('scopeId'), optional('project'), optional('name'), optional('description'), optional('slug'), optional('position'), ...sourceTimestampArgs],
  },
  {
    toolId: 'projectman-kanban-board-reorder',
    operationId: 'kanban-board.reorder',
    summary: 'Reorder kanban boards in a project.',
    args: [optional('scopeId'), optional('project'), required('orderedIds')],
  },
  {
    toolId: 'projectman-kanban-board-delete',
    operationId: 'kanban-board.delete',
    summary: 'Delete a kanban board by id.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-kanban-board-archive',
    operationId: 'kanban-board.archive',
    summary: 'Archive a board (soft).',
    args: [required('id')],
  },
  {
    toolId: 'projectman-kanban-board-unarchive',
    operationId: 'kanban-board.unarchive',
    summary: 'Unarchive a board.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-kanban-column-list',
    operationId: 'kanban-column.list',
    summary: 'List raw kanban column records in the current scope.',
    args: [optional('name'), optional('slug')],
  },
  {
    toolId: 'projectman-kanban-column-get',
    operationId: 'kanban-column.get',
    summary: 'Get a kanban column record by id.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-kanban-column-create',
    operationId: 'kanban-column.create',
    summary: 'Create a kanban column record.',
    args: [required('name'), optional('slug'), optional('description'), optional('wipLimit')],
  },
  {
    toolId: 'projectman-kanban-column-update',
    operationId: 'kanban-column.update',
    summary: 'Patch a kanban column record.',
    args: [required('id'), optional('name'), optional('slug'), optional('description'), optional('wipLimit')],
  },
  {
    toolId: 'projectman-kanban-column-set-wip-limit',
    operationId: 'kanban-column.set-wip-limit',
    summary: 'Set WIP limit for a kanban column record.',
    args: [required('id'), required('wipLimit')],
  },
  {
    toolId: 'projectman-kanban-column-delete',
    operationId: 'kanban-column.delete',
    summary: 'Delete a kanban column record.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-kanban-board-column-list',
    operationId: 'kanban-board-column.list',
    summary: 'List board column placements on a board.',
    args: [required('board')],
  },
  {
    toolId: 'projectman-kanban-board-column-create',
    operationId: 'kanban-board-column.create',
    summary: 'Attach a column to a board.',
    args: [required('board'), required('column'), optional('position')],
  },
  {
    toolId: 'projectman-kanban-board-column-update',
    operationId: 'kanban-board-column.update',
    summary: 'Patch a board column placement.',
    args: [required('id'), optional('column'), optional('position')],
  },
  {
    toolId: 'projectman-kanban-board-column-reorder',
    operationId: 'kanban-board-column.reorder',
    summary: 'Reorder board column placements.',
    args: [required('board'), required('orderedIds')],
  },
  {
    toolId: 'projectman-kanban-board-column-delete',
    operationId: 'kanban-board-column.delete',
    summary: 'Delete a board column placement.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-kanban-task-list',
    operationId: 'kanban-task.list',
    summary: 'List kanban tasks by filters.',
    args: [optional('scopeId'), optional('project'), optional('board'), optional('boardColumn'), optional('sprint')],
  },
  {
    toolId: 'projectman-kanban-task-get',
    operationId: 'kanban-task.get',
    summary: 'Get a kanban task by id.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-kanban-task-create',
    operationId: 'kanban-task.create',
    summary: 'Create a kanban task.',
    args: [optional('scopeId'), optional('project'), required('board'), required('boardColumn'), required('title'), optional('description'), optional('position'), ...sourceTimestampArgs],
  },
  {
    toolId: 'projectman-kanban-task-update',
    operationId: 'kanban-task.update',
    summary: 'Patch a kanban task.',
    args: [required('id'), optional('title'), optional('description'), optional('progress'), optional('sprint'), ...sourceTimestampArgs],
  },
  {
    toolId: 'projectman-kanban-task-move',
    operationId: 'kanban-task.move',
    summary: 'Move a kanban task to another board column.',
    args: [required('id'), required('boardColumn'), optional('position')],
  },
  {
    toolId: 'projectman-kanban-task-reorder',
    operationId: 'kanban-task.reorder',
    summary: 'Reorder kanban tasks inside a board column.',
    args: [required('boardColumn'), required('orderedIds')],
  },
  {
    toolId: 'projectman-kanban-task-delete',
    operationId: 'kanban-task.delete',
    summary: 'Delete a kanban task.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-sprint-list',
    operationId: 'sprint.list',
    summary: 'List task-scoped sprint execution documents.',
    args: [optional('scopeId'), optional('project'), optional('kanbanTask'), optional('name'), optional('includeArchived')],
  },
  {
    toolId: 'projectman-sprint-get',
    operationId: 'sprint.get',
    summary: 'Get a sprint execution document by id.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-sprint-create',
    operationId: 'sprint.create',
    summary: 'Create a task-scoped sprint execution document.',
    args: [
      optional('scopeId'),
      optional('project'),
      required('kanbanTask'),
      required('name'),
      required('goal'),
      optional('references'),
      optional('scope'),
      optional('validationPlan'),
      optional('notes'),
      optional('phases'),
      ...sourceTimestampArgs,
    ],
  },
  {
    toolId: 'projectman-sprint-update-plan',
    operationId: 'sprint.update-plan',
    summary: 'Save the nested sprint plan, phases, and microtasks.',
    args: [required('id'), optional('name'), optional('goal'), optional('references'), optional('scope'), optional('validationPlan'), optional('notes'), optional('phases'), optional('expectedUpdatedAt'), ...sourceTimestampArgs],
  },
  {
    toolId: 'projectman-sprint-update-microtask-status',
    operationId: 'sprint.update-microtask-status',
    summary: 'Update a sprint microtask status inside its sprint snapshot.',
    args: [required('id'), required('microTask'), required('status')],
  },
  {
    toolId: 'projectman-sprint-add-microtask',
    operationId: 'sprint.add-microtask',
    summary: 'Append or insert a microtask into a sprint phase without replacing the full plan.',
    args: [
      required('id'),
      optional('phaseId'),
      optional('phase'),
      required('title'),
      optional('status'),
      optional('position'),
      optional('notes'),
      optional('createdBy'),
      optional('updatedBy'),
    ],
  },
  {
    toolId: 'projectman-sprint-update-microtask',
    operationId: 'sprint.update-microtask',
    summary: 'Patch a sprint microtask without replacing sibling phases or microtasks.',
    args: [required('id'), required('microTask'), optional('title'), optional('status'), optional('position'), optional('notes'), optional('updatedBy')],
  },
  {
    toolId: 'projectman-sprint-delete-microtask',
    operationId: 'sprint.delete-microtask',
    summary: 'Delete a sprint microtask and compact remaining phase positions.',
    args: [required('id'), required('microTask'), optional('updatedBy')],
  },
  {
    toolId: 'projectman-sprint-delete',
    operationId: 'sprint.delete',
    summary: 'Delete a sprint execution document.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-sprint-archive',
    operationId: 'sprint.archive',
    summary: 'Archive a sprint (soft).',
    args: [required('id')],
  },
  {
    toolId: 'projectman-sprint-unarchive',
    operationId: 'sprint.unarchive',
    summary: 'Unarchive a sprint.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-implementation-plan-list',
    operationId: 'implementation-plan.list',
    summary: 'List sprint-backed implementation plans.',
    args: [optional('scopeId'), optional('project'), optional('kanbanTask'), optional('name'), optional('includeArchived')],
  },
  {
    toolId: 'projectman-implementation-plan-get',
    operationId: 'implementation-plan.get',
    summary: 'Get a sprint-backed implementation plan by id.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-implementation-plan-create',
    operationId: 'implementation-plan.create',
    summary: 'Create a sprint-backed implementation plan.',
    args: [
      optional('scopeId'),
      optional('project'),
      required('kanbanTask'),
      required('name'),
      required('goal'),
      optional('references'),
      optional('scope'),
      optional('validationPlan'),
      optional('notes'),
      optional('phases'),
      ...sourceTimestampArgs,
    ],
  },
  {
    toolId: 'projectman-implementation-plan-update',
    operationId: 'implementation-plan.update',
    summary: 'Update the sprint-backed implementation plan snapshot.',
    args: [required('id'), optional('name'), optional('goal'), optional('references'), optional('scope'), optional('validationPlan'), optional('notes'), optional('phases'), optional('expectedUpdatedAt'), ...sourceTimestampArgs],
  },
  {
    toolId: 'projectman-implementation-plan-add-microtask',
    operationId: 'implementation-plan.add-microtask',
    summary: 'Append or insert a microtask into a sprint-backed implementation plan phase.',
    args: [
      required('id'),
      optional('phaseId'),
      optional('phase'),
      required('title'),
      optional('status'),
      optional('position'),
      optional('notes'),
      optional('createdBy'),
      optional('updatedBy'),
    ],
  },
  {
    toolId: 'projectman-implementation-plan-update-microtask',
    operationId: 'implementation-plan.update-microtask',
    summary: 'Patch one microtask inside a sprint-backed implementation plan.',
    args: [required('id'), required('microTask'), optional('title'), optional('status'), optional('position'), optional('notes'), optional('updatedBy')],
  },
  {
    toolId: 'projectman-implementation-plan-delete-microtask',
    operationId: 'implementation-plan.delete-microtask',
    summary: 'Delete a microtask from a sprint-backed implementation plan.',
    args: [required('id'), required('microTask'), optional('updatedBy')],
  },
  {
    toolId: 'projectman-issue-list',
    operationId: 'issue.list',
    summary: 'List issues by filters.',
    args: [optional('scopeId'), optional('project'), optional('sprint'), optional('kanbanTask'), optional('microTask'), optional('reviewRequest'), optional('status'), optional('severity'), optional('source'), optional('tags')],
  },
  {
    toolId: 'projectman-issue-get',
    operationId: 'issue.get',
    summary: 'Get an issue by id.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-issue-create',
    operationId: 'issue.create',
    summary: 'Create an issue.',
    args: [optional('scopeId'), optional('project'), required('title'), optional('description'), optional('status'), optional('severity'), optional('source'), optional('sprint'), optional('kanbanTask'), optional('microTask'), optional('reviewRequest'), optional('tags'), optional('notes'), ...sourceTimestampArgs],
  },
  {
    toolId: 'projectman-issue-update',
    operationId: 'issue.update',
    summary: 'Patch an issue.',
    args: [required('id'), optional('title'), optional('description'), optional('status'), optional('severity'), optional('source'), optional('sprint'), optional('kanbanTask'), optional('microTask'), optional('reviewRequest'), optional('tags'), optional('notes'), optional('resolvedAt'), ...sourceTimestampArgs],
  },
  {
    toolId: 'projectman-issue-delete',
    operationId: 'issue.delete',
    summary: 'Delete an issue.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-feedback-list',
    operationId: 'feedback.list',
    summary: 'List feedback items by filters.',
    args: [optional('scopeId'), optional('project'), optional('sprint'), optional('kanbanTask'), optional('microTask'), optional('status'), optional('type'), optional('severity'), optional('source'), optional('tags')],
  },
  {
    toolId: 'projectman-feedback-get',
    operationId: 'feedback.get',
    summary: 'Get a feedback item by id.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-feedback-create',
    operationId: 'feedback.create',
    summary: 'Create a feedback item.',
    args: [optional('scopeId'), optional('project'), required('title'), optional('description'), optional('status'), optional('type'), optional('severity'), optional('source'), optional('sprint'), optional('kanbanTask'), optional('microTask'), optional('tags'), optional('suggestion'), optional('notes'), ...sourceTimestampArgs],
  },
  {
    toolId: 'projectman-feedback-update',
    operationId: 'feedback.update',
    summary: 'Patch a feedback item.',
    args: [required('id'), optional('title'), optional('description'), optional('status'), optional('type'), optional('severity'), optional('source'), optional('sprint'), optional('kanbanTask'), optional('microTask'), optional('tags'), optional('suggestion'), optional('notes'), ...sourceTimestampArgs],
  },
  {
    toolId: 'projectman-feedback-delete',
    operationId: 'feedback.delete',
    summary: 'Delete a feedback item.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-review-request-list',
    operationId: 'review-request.list',
    summary: 'List PM-backed review requests by filters.',
    args: [
      optional('scopeId'),
      optional('project'),
      optional('sprint'),
      optional('kanbanTask'),
      optional('microTask'),
      optional('collabSession'),
      optional('status'),
      optional('priority'),
      optional('source'),
      optional('targetAgent'),
      optional('targetSlot'),
      optional('parentReviewRequest'),
      optional('rootReviewRequest'),
      optional('tags'),
    ],
  },
  {
    toolId: 'projectman-review-request-get',
    operationId: 'review-request.get',
    summary: 'Get a PM-backed review request by id.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-review-request-create',
    operationId: 'review-request.create',
    summary: 'Create a PM-backed review request.',
    args: [
      optional('scopeId'),
      optional('project'),
      required('title'),
      optional('description'),
      optional('reviewScope'),
      optional('instructions'),
      optional('references'),
      optional('status'),
      optional('priority'),
      optional('source'),
      optional('sprint'),
      optional('kanbanTask'),
      optional('microTask'),
      optional('collabSession'),
      optional('collabRequestEvent'),
      optional('collabResultEventIds'),
      optional('requestedBy'),
      optional('targetAgent'),
      optional('targetSlot'),
      optional('parentReviewRequest'),
      optional('rootReviewRequest'),
      optional('tags'),
      optional('notes'),
      optional('meta'),
      optional('idempotencyKey'),
      optional('requestedAt'),
      ...sourceTimestampArgs,
    ],
  },
  {
    toolId: 'projectman-review-request-update',
    operationId: 'review-request.update',
    summary: 'Patch a PM-backed review request.',
    args: [
      required('id'),
      optional('title'),
      optional('description'),
      optional('reviewScope'),
      optional('instructions'),
      optional('references'),
      optional('priority'),
      optional('source'),
      optional('sprint'),
      optional('kanbanTask'),
      optional('microTask'),
      optional('collabSession'),
      optional('collabRequestEvent'),
      optional('requestedBy'),
      optional('targetAgent'),
      optional('targetSlot'),
      optional('tags'),
      optional('notes'),
      optional('meta'),
      optional('requestedAt'),
      optional('closedAt'),
      ...sourceTimestampArgs,
    ],
  },
  {
    toolId: 'projectman-review-request-delete',
    operationId: 'review-request.delete',
    summary: 'Delete a PM-backed review request.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-review-request-add-result',
    operationId: 'review-request.add-result',
    summary: 'Append an immutable review result to a PM-backed review request.',
    args: [
      required('id'),
      required('reviewer'),
      required('outcome'),
      required('summary'),
      optional('positives'),
      optional('concerns'),
      optional('objections'),
      optional('references'),
      optional('issueIds'),
      optional('basedOnSeqRange'),
      optional('resultId'),
      optional('resultCreatedAt'),
      optional('collabResultEventId'),
      optional('idempotencyKey'),
    ],
  },
  {
    toolId: 'projectman-kanban-template-list',
    operationId: 'kanban-template.list',
    summary: 'List kanban templates.',
    args: [optional('name')],
  },
  {
    toolId: 'projectman-kanban-template-create',
    operationId: 'kanban-template.create',
    summary: 'Create a kanban template.',
    args: [required('name'), optional('description'), required('definition')],
  },
  {
    toolId: 'projectman-kanban-template-update',
    operationId: 'kanban-template.update',
    summary: 'Patch a kanban template.',
    args: [required('id'), optional('name'), optional('description'), optional('definition')],
  },
  {
    toolId: 'projectman-kanban-template-delete',
    operationId: 'kanban-template.delete',
    summary: 'Delete a kanban template.',
    args: [required('id')],
  },
  {
    toolId: 'projectman-kanban-template-apply',
    operationId: 'kanban-template.apply',
    summary: 'Apply a kanban template to a project.',
    args: [required('id'), optional('scopeId'), optional('project')],
  },
  {
    toolId: 'projectman-event-list',
    operationId: 'event.list',
    summary: 'List Projectman audit events.',
    args: [optional('scopeId'), optional('project'), optional('entityType'), optional('entityId'), optional('action')],
  },
  {
    toolId: 'projectman-event-delete',
    operationId: 'event.delete',
    summary: 'Delete a Projectman audit event.',
    args: [required('id')],
  },
]
