import { InferSelectModel } from 'drizzle-orm'
import { index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core'
import { randomUUID } from 'node:crypto'
import { domainTableName } from '../../domain-naming.js'

export const documentIndexEntryTableSqlite = sqliteTable(
  domainTableName('document_index_entries'),
  {
    id: text().primaryKey().$defaultFn(() => randomUUID()),
    tenantId: text().notNull(),
    documentVersionId: text().notNull(),
    documentId: text().notNull(),
    locale: text().notNull().default(''),
    fallbackLocale: text().notNull().default(''),
    itemKind: text().notNull(),
    sortOrder: integer().notNull(),
    buildFingerprint: text().notNull(),
    linkId: text(),
    parentLinkId: text(),
    anchor: text().notNull(),
    parentAnchor: text(),
    number: text(),
    depth: integer().notNull(),
    position: integer().notNull(),
    title: text().notNull(),
    breadcrumb: text().notNull(),
    titleVisible: integer({ mode: 'boolean' }).notNull().default(true),
    pageBreakBefore: integer({ mode: 'boolean' }).notNull().default(false),
    pageBreakAfter: integer({ mode: 'boolean' }).notNull().default(false),
    sectionId: text(),
    sectionUid: text(),
    sectionSlug: text(),
    pageId: text(),
    pageUid: text(),
    pageVersionId: text(),
    format: text(),
    pageNumberStart: integer(),
    pageNumberEnd: integer(),
    bodyText: text(),
    summaryText: text(),
    sourceCharCount: integer().notNull().default(0),
    sourceWordCount: integer().notNull().default(0),
    summaryCharCount: integer().notNull().default(0),
    summaryWordCount: integer().notNull().default(0),
    searchText: text().notNull(),
    embeddingProvider: text(),
    embeddingModel: text(),
    embeddingHash: text(),
    embeddingDimensions: integer(),
    embeddingVector: text(),
    createdBy: text(),
    updatedBy: text(),
    createdAt: integer({ mode: 'timestamp_ms' }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer({ mode: 'timestamp_ms' }).notNull().$defaultFn(() => new Date()),
  },
  (t) => [
    uniqueIndex('doc_index_entry_sort_unique').on(
      t.tenantId,
      t.documentVersionId,
      t.locale,
      t.fallbackLocale,
      t.sortOrder,
    ),
    uniqueIndex('doc_index_entry_anchor_unique').on(
      t.tenantId,
      t.documentVersionId,
      t.locale,
      t.fallbackLocale,
      t.anchor,
    ),
    index('doc_index_entry_idx_doc_version').on(t.tenantId, t.documentVersionId, t.locale, t.fallbackLocale),
    index('doc_index_entry_idx_link').on(t.tenantId, t.linkId),
    index('doc_index_entry_idx_page_version').on(t.tenantId, t.pageVersionId),
    index('doc_index_entry_idx_section').on(t.tenantId, t.sectionId),
  ],
)

export type IdbDocumentIndexEntryDrizzleSqlite = InferSelectModel<typeof documentIndexEntryTableSqlite>
export type DocumentIndexEntryColumnsDrizzleSqlite = keyof IdbDocumentIndexEntryDrizzleSqlite
