import { InferSelectModel } from 'drizzle-orm'
import { boolean, index, integer, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core'
import { domainTableName } from '../../domain-naming.js'

export const documentIndexEntryTable = pgTable(
  domainTableName('document_index_entries'),
  {
    id: uuid().primaryKey().defaultRandom(),
    tenantId: text().notNull(),
    documentVersionId: uuid().notNull(),
    documentId: uuid().notNull(),
    locale: text().notNull().default(''),
    fallbackLocale: text().notNull().default(''),
    itemKind: text().notNull(),
    sortOrder: integer().notNull(),
    buildFingerprint: text().notNull(),
    linkId: uuid(),
    parentLinkId: uuid(),
    anchor: text().notNull(),
    parentAnchor: text(),
    number: text(),
    depth: integer().notNull(),
    position: integer().notNull(),
    title: text().notNull(),
    breadcrumb: text().notNull(),
    titleVisible: boolean().notNull().default(true),
    pageBreakBefore: boolean().notNull().default(false),
    pageBreakAfter: boolean().notNull().default(false),
    sectionId: uuid(),
    sectionUid: text(),
    sectionSlug: text(),
    pageId: uuid(),
    pageUid: text(),
    pageVersionId: uuid(),
    format: text(),
    pageNumberStart: integer(),
    pageNumberEnd: integer(),
    bodyText: text(),
    summaryText: text(),
    sourceCharCount: integer().notNull().default(0),
    sourceWordCount: integer().notNull().default(0),
    summaryCharCount: integer().notNull().default(0),
    summaryWordCount: integer().notNull().default(0),
    searchText: text().notNull(),
    embeddingProvider: text(),
    embeddingModel: text(),
    embeddingHash: text(),
    embeddingDimensions: integer(),
    embeddingVector: text(),
    createdBy: text(),
    updatedBy: text(),
    createdAt: timestamp({ withTimezone: true }).defaultNow(),
    updatedAt: timestamp({ withTimezone: true }).defaultNow(),
  },
  (t) => [
    uniqueIndex('doc_index_entry_sort_unique').on(
      t.tenantId,
      t.documentVersionId,
      t.locale,
      t.fallbackLocale,
      t.sortOrder,
    ),
    uniqueIndex('doc_index_entry_anchor_unique').on(
      t.tenantId,
      t.documentVersionId,
      t.locale,
      t.fallbackLocale,
      t.anchor,
    ),
    index('doc_index_entry_idx_doc_version').on(t.tenantId, t.documentVersionId, t.locale, t.fallbackLocale),
    index('doc_index_entry_idx_link').on(t.tenantId, t.linkId),
    index('doc_index_entry_idx_page_version').on(t.tenantId, t.pageVersionId),
    index('doc_index_entry_idx_section').on(t.tenantId, t.sectionId),
  ],
)

export type IdbDocumentIndexEntryDrizzle = InferSelectModel<typeof documentIndexEntryTable>
export type DocumentIndexEntryColumnsDrizzle = keyof IdbDocumentIndexEntryDrizzle
