import type { XfLogger } from '@aopslab/xf-logger'
import { Effect } from 'effect'
import {
  cacheKeyFromLocale,
  CountersMetricsCollector,
  LoggerMetricsCollector,
  MultiMetricsCollector,
  inferRepoType,
  parseEnvConfig,
} from '@aopslab/xf-dm-kits'

import type { AgentspaceKitEnvConfig } from '../config/config.js'
import type { AgentspaceKitProvider, AgentspaceKitProviderOptions, AgentspaceKitContext, AgentspaceKitStaticConfig } from './types.js'
import { createAgentspaceKitProvider } from './provider.js'

export interface CreateAgentspaceKitOptions extends Omit<AgentspaceKitProviderOptions, 'getCacheKey'> {
  name?: string
  getCacheKey?: (context: AgentspaceKitContext) => string | null
}

export function createAgentspaceKit(options: CreateAgentspaceKitOptions) {
  const provider: AgentspaceKitProvider = createAgentspaceKitProvider({
    ...options,
    getCacheKey: options.getCacheKey ?? ((ctx) => cacheKeyFromLocale(ctx.locale, ctx.fallbackLocale)),
  })

  return {
    getStaticConfig(): AgentspaceKitStaticConfig {
      return options.staticConfig
    },
    getAgentProfileService: provider.getAgentProfileService,
    createAgentProfileService: provider.createAgentProfileService,
    getProjectService: provider.getProjectService,
    createProjectService: provider.createProjectService,
    getProjectPathService: provider.getProjectPathService,
    createProjectPathService: provider.createProjectPathService,
    getProjectMemberService: provider.getProjectMemberService,
    createProjectMemberService: provider.createProjectMemberService,
    getPromptService: provider.getPromptService,
    createPromptService: provider.createPromptService,
    getPromptVersionService: provider.getPromptVersionService,
    createPromptVersionService: provider.createPromptVersionService,
    getResourceService: provider.getResourceService,
    createResourceService: provider.createResourceService,
    getSkillService: provider.getSkillService,
    createSkillService: provider.createSkillService,
    getSkillVersionService: provider.getSkillVersionService,
    createSkillVersionService: provider.createSkillVersionService,
    getKanbanBoardService: provider.getKanbanBoardService,
    createKanbanBoardService: provider.createKanbanBoardService,
    getKanbanColumnService: provider.getKanbanColumnService,
    createKanbanColumnService: provider.createKanbanColumnService,
    getSprintService: provider.getSprintService,
    createSprintService: provider.createSprintService,
    getSprintItemService: provider.getSprintItemService,
    createSprintItemService: provider.createSprintItemService,
    getTaskService: provider.getTaskService,
    createTaskService: provider.createTaskService,
    getTaskCommentService: provider.getTaskCommentService,
    createTaskCommentService: provider.createTaskCommentService,
    getAgentSessionService: provider.getAgentSessionService,
    createAgentSessionService: provider.createAgentSessionService,
    getAgentRunService: provider.getAgentRunService,
    createAgentRunService: provider.createAgentRunService,
    getAgentRunEventService: provider.getAgentRunEventService,
    createAgentRunEventService: provider.createAgentRunEventService,
    getActivityItemService: provider.getActivityItemService,
    createActivityItemService: provider.createActivityItemService,
    getArtifactService: provider.getArtifactService,
    createArtifactService: provider.createArtifactService,
    getArtifactLinkService: provider.getArtifactLinkService,
    createArtifactLinkService: provider.createArtifactLinkService,
    getCodexChatThreadService: provider.getCodexChatThreadService,
    createCodexChatThreadService: provider.createCodexChatThreadService,
    getCodexChatMessageService: provider.getCodexChatMessageService,
    createCodexChatMessageService: provider.createCodexChatMessageService,
    getCodexChatSettingService: provider.getCodexChatSettingService,
    createCodexChatSettingService: provider.createCodexChatSettingService,
    getChatService: provider.getChatService,
    createChatService: provider.createChatService,
    getDiscussionService: provider.getDiscussionService,
    createDiscussionService: provider.createDiscussionService,
    getExperienceItemService: provider.getExperienceItemService,
    createExperienceItemService: provider.createExperienceItemService,
    getMemoryItemService: provider.getMemoryItemService,
    createMemoryItemService: provider.createMemoryItemService,
    getMissionService: provider.getMissionService,
    createMissionService: provider.createMissionService,
    getTagService: provider.getTagService,
    createTagService: provider.createTagService,
    getWorkflowDefinitionService: provider.getWorkflowDefinitionService,
    createWorkflowDefinitionService: provider.createWorkflowDefinitionService,
    getWorkflowInstanceService: provider.getWorkflowInstanceService,
    createWorkflowInstanceService: provider.createWorkflowInstanceService,
    getWorkflowStepRunService: provider.getWorkflowStepRunService,
    createWorkflowStepRunService: provider.createWorkflowStepRunService,
    getAgentProfileRepository: provider.getAgentProfileRepository,
    getProjectRepository: provider.getProjectRepository,
    getProjectPathRepository: provider.getProjectPathRepository,
    getScopeRepository: provider.getScopeRepository,
    getProjectMemberRepository: provider.getProjectMemberRepository,
    getPromptRepository: provider.getPromptRepository,
    getPromptVersionRepository: provider.getPromptVersionRepository,
    getResourceRepository: provider.getResourceRepository,
    getSkillRepository: provider.getSkillRepository,
    getSkillVersionRepository: provider.getSkillVersionRepository,
    getKanbanBoardRepository: provider.getKanbanBoardRepository,
    getKanbanColumnRepository: provider.getKanbanColumnRepository,
    getSprintRepository: provider.getSprintRepository,
    getSprintItemRepository: provider.getSprintItemRepository,
    getTaskRepository: provider.getTaskRepository,
    getTaskCommentRepository: provider.getTaskCommentRepository,
    getAgentSessionRepository: provider.getAgentSessionRepository,
    getAgentRunRepository: provider.getAgentRunRepository,
    getAgentRunEventRepository: provider.getAgentRunEventRepository,
    getArtifactRepository: provider.getArtifactRepository,
    getArtifactLinkRepository: provider.getArtifactLinkRepository,
    getCodexChatThreadRepository: provider.getCodexChatThreadRepository,
    getCodexChatMessageRepository: provider.getCodexChatMessageRepository,
    getCodexChatSettingRepository: provider.getCodexChatSettingRepository,
    getChatRoomRepository: provider.getChatRoomRepository,
    getChatRoomMemberRepository: provider.getChatRoomMemberRepository,
    getChatRoomBindingRepository: provider.getChatRoomBindingRepository,
    getChatMessageRepository: provider.getChatMessageRepository,
    getDiscussionTopicRepository: provider.getDiscussionTopicRepository,
    getDiscussionTurnRepository: provider.getDiscussionTurnRepository,
    getDiscussionOutputRepository: provider.getDiscussionOutputRepository,
    getExperienceItemRepository: provider.getExperienceItemRepository,
    getMemoryItemRepository: provider.getMemoryItemRepository,
    getMissionRepository: provider.getMissionRepository,
    getTagRepository: provider.getTagRepository,
    getWorkflowDefinitionRepository: provider.getWorkflowDefinitionRepository,
    getWorkflowInstanceRepository: provider.getWorkflowInstanceRepository,
    getWorkflowStepRunRepository: provider.getWorkflowStepRunRepository,
    getAll: provider.getAll,
    createAll: provider.createAll,
    clearServiceCache: provider.clearServiceCache,
    clearAgentProfileServiceCache: provider.clearAgentProfileServiceCache,
    clearProjectServiceCache: provider.clearProjectServiceCache,
    clearProjectPathServiceCache: provider.clearProjectPathServiceCache,
    clearProjectMemberServiceCache: provider.clearProjectMemberServiceCache,
    clearPromptServiceCache: provider.clearPromptServiceCache,
    clearPromptVersionServiceCache: provider.clearPromptVersionServiceCache,
    clearResourceServiceCache: provider.clearResourceServiceCache,
    clearSkillServiceCache: provider.clearSkillServiceCache,
    clearSkillVersionServiceCache: provider.clearSkillVersionServiceCache,
    clearKanbanBoardServiceCache: provider.clearKanbanBoardServiceCache,
    clearKanbanColumnServiceCache: provider.clearKanbanColumnServiceCache,
    clearSprintServiceCache: provider.clearSprintServiceCache,
    clearSprintItemServiceCache: provider.clearSprintItemServiceCache,
    clearTaskServiceCache: provider.clearTaskServiceCache,
    clearTaskCommentServiceCache: provider.clearTaskCommentServiceCache,
    clearAgentSessionServiceCache: provider.clearAgentSessionServiceCache,
    clearAgentRunServiceCache: provider.clearAgentRunServiceCache,
    clearAgentRunEventServiceCache: provider.clearAgentRunEventServiceCache,
    clearActivityItemServiceCache: provider.clearActivityItemServiceCache,
    clearArtifactServiceCache: provider.clearArtifactServiceCache,
    clearArtifactLinkServiceCache: provider.clearArtifactLinkServiceCache,
    clearCodexChatThreadServiceCache: provider.clearCodexChatThreadServiceCache,
    clearCodexChatMessageServiceCache: provider.clearCodexChatMessageServiceCache,
    clearCodexChatSettingServiceCache: provider.clearCodexChatSettingServiceCache,
    clearChatServiceCache: provider.clearChatServiceCache,
    clearDiscussionServiceCache: provider.clearDiscussionServiceCache,
    clearExperienceItemServiceCache: provider.clearExperienceItemServiceCache,
    clearMemoryItemServiceCache: provider.clearMemoryItemServiceCache,
    clearMissionServiceCache: provider.clearMissionServiceCache,
    clearTagServiceCache: provider.clearTagServiceCache,
    clearWorkflowDefinitionServiceCache: provider.clearWorkflowDefinitionServiceCache,
    clearWorkflowInstanceServiceCache: provider.clearWorkflowInstanceServiceCache,
    clearWorkflowStepRunServiceCache: provider.clearWorkflowStepRunServiceCache,
    reset: provider.reset,
    getRegistryStats: provider.getRegistryStats,
    resolveLogger: provider.resolveLogger,

    withContext(overrides: Partial<AgentspaceKitContext>) {
      return {
        getStaticConfig(): AgentspaceKitStaticConfig {
          return options.staticConfig
        },
        getAgentProfileService: (o?: Partial<AgentspaceKitContext>) => provider.getAgentProfileService({ ...overrides, ...o }),
        getProjectService: (o?: Partial<AgentspaceKitContext>) => provider.getProjectService({ ...overrides, ...o }),
        getProjectPathService: (o?: Partial<AgentspaceKitContext>) => provider.getProjectPathService({ ...overrides, ...o }),
        getProjectMemberService: (o?: Partial<AgentspaceKitContext>) => provider.getProjectMemberService({ ...overrides, ...o }),
        getPromptService: (o?: Partial<AgentspaceKitContext>) => provider.getPromptService({ ...overrides, ...o }),
        getPromptVersionService: (o?: Partial<AgentspaceKitContext>) => provider.getPromptVersionService({ ...overrides, ...o }),
        getResourceService: (o?: Partial<AgentspaceKitContext>) => provider.getResourceService({ ...overrides, ...o }),
        getSkillService: (o?: Partial<AgentspaceKitContext>) => provider.getSkillService({ ...overrides, ...o }),
        getSkillVersionService: (o?: Partial<AgentspaceKitContext>) => provider.getSkillVersionService({ ...overrides, ...o }),
        getKanbanBoardService: (o?: Partial<AgentspaceKitContext>) => provider.getKanbanBoardService({ ...overrides, ...o }),
        getKanbanColumnService: (o?: Partial<AgentspaceKitContext>) => provider.getKanbanColumnService({ ...overrides, ...o }),
        getSprintService: (o?: Partial<AgentspaceKitContext>) => provider.getSprintService({ ...overrides, ...o }),
        getSprintItemService: (o?: Partial<AgentspaceKitContext>) => provider.getSprintItemService({ ...overrides, ...o }),
        getTaskService: (o?: Partial<AgentspaceKitContext>) => provider.getTaskService({ ...overrides, ...o }),
        getTaskCommentService: (o?: Partial<AgentspaceKitContext>) => provider.getTaskCommentService({ ...overrides, ...o }),
        getAgentSessionService: (o?: Partial<AgentspaceKitContext>) => provider.getAgentSessionService({ ...overrides, ...o }),
        getAgentRunService: (o?: Partial<AgentspaceKitContext>) => provider.getAgentRunService({ ...overrides, ...o }),
        getAgentRunEventService: (o?: Partial<AgentspaceKitContext>) => provider.getAgentRunEventService({ ...overrides, ...o }),
        getActivityItemService: (o?: Partial<AgentspaceKitContext>) => provider.getActivityItemService({ ...overrides, ...o }),
        getArtifactService: (o?: Partial<AgentspaceKitContext>) => provider.getArtifactService({ ...overrides, ...o }),
        getArtifactLinkService: (o?: Partial<AgentspaceKitContext>) => provider.getArtifactLinkService({ ...overrides, ...o }),
        getCodexChatThreadService: (o?: Partial<AgentspaceKitContext>) => provider.getCodexChatThreadService({ ...overrides, ...o }),
        getCodexChatMessageService: (o?: Partial<AgentspaceKitContext>) => provider.getCodexChatMessageService({ ...overrides, ...o }),
        getCodexChatSettingService: (o?: Partial<AgentspaceKitContext>) => provider.getCodexChatSettingService({ ...overrides, ...o }),
        getChatService: (o?: Partial<AgentspaceKitContext>) => provider.getChatService({ ...overrides, ...o }),
        getDiscussionService: (o?: Partial<AgentspaceKitContext>) => provider.getDiscussionService({ ...overrides, ...o }),
        getExperienceItemService: (o?: Partial<AgentspaceKitContext>) => provider.getExperienceItemService({ ...overrides, ...o }),
        getMemoryItemService: (o?: Partial<AgentspaceKitContext>) => provider.getMemoryItemService({ ...overrides, ...o }),
        getMissionService: (o?: Partial<AgentspaceKitContext>) => provider.getMissionService({ ...overrides, ...o }),
        getTagService: (o?: Partial<AgentspaceKitContext>) => provider.getTagService({ ...overrides, ...o }),
        getWorkflowDefinitionService: (o?: Partial<AgentspaceKitContext>) => provider.getWorkflowDefinitionService({ ...overrides, ...o }),
        getWorkflowInstanceService: (o?: Partial<AgentspaceKitContext>) => provider.getWorkflowInstanceService({ ...overrides, ...o }),
        getWorkflowStepRunService: (o?: Partial<AgentspaceKitContext>) => provider.getWorkflowStepRunService({ ...overrides, ...o }),
        getAgentProfileRepository: (o?: Partial<AgentspaceKitContext>) => provider.getAgentProfileRepository({ ...overrides, ...o }),
        getProjectRepository: (o?: Partial<AgentspaceKitContext>) => provider.getProjectRepository({ ...overrides, ...o }),
        getProjectPathRepository: (o?: Partial<AgentspaceKitContext>) => provider.getProjectPathRepository({ ...overrides, ...o }),
        getScopeRepository: (o?: Partial<AgentspaceKitContext>) => provider.getScopeRepository({ ...overrides, ...o }),
        getProjectMemberRepository: (o?: Partial<AgentspaceKitContext>) => provider.getProjectMemberRepository({ ...overrides, ...o }),
        getPromptRepository: (o?: Partial<AgentspaceKitContext>) => provider.getPromptRepository({ ...overrides, ...o }),
        getPromptVersionRepository: (o?: Partial<AgentspaceKitContext>) => provider.getPromptVersionRepository({ ...overrides, ...o }),
        getResourceRepository: (o?: Partial<AgentspaceKitContext>) => provider.getResourceRepository({ ...overrides, ...o }),
        getSkillRepository: (o?: Partial<AgentspaceKitContext>) => provider.getSkillRepository({ ...overrides, ...o }),
        getSkillVersionRepository: (o?: Partial<AgentspaceKitContext>) => provider.getSkillVersionRepository({ ...overrides, ...o }),
        getKanbanBoardRepository: (o?: Partial<AgentspaceKitContext>) => provider.getKanbanBoardRepository({ ...overrides, ...o }),
        getKanbanColumnRepository: (o?: Partial<AgentspaceKitContext>) => provider.getKanbanColumnRepository({ ...overrides, ...o }),
        getSprintRepository: (o?: Partial<AgentspaceKitContext>) => provider.getSprintRepository({ ...overrides, ...o }),
        getSprintItemRepository: (o?: Partial<AgentspaceKitContext>) => provider.getSprintItemRepository({ ...overrides, ...o }),
        getTaskRepository: (o?: Partial<AgentspaceKitContext>) => provider.getTaskRepository({ ...overrides, ...o }),
        getTaskCommentRepository: (o?: Partial<AgentspaceKitContext>) => provider.getTaskCommentRepository({ ...overrides, ...o }),
        getAgentSessionRepository: (o?: Partial<AgentspaceKitContext>) => provider.getAgentSessionRepository({ ...overrides, ...o }),
        getAgentRunRepository: (o?: Partial<AgentspaceKitContext>) => provider.getAgentRunRepository({ ...overrides, ...o }),
        getAgentRunEventRepository: (o?: Partial<AgentspaceKitContext>) => provider.getAgentRunEventRepository({ ...overrides, ...o }),
        getArtifactRepository: (o?: Partial<AgentspaceKitContext>) => provider.getArtifactRepository({ ...overrides, ...o }),
        getArtifactLinkRepository: (o?: Partial<AgentspaceKitContext>) => provider.getArtifactLinkRepository({ ...overrides, ...o }),
        getCodexChatThreadRepository: (o?: Partial<AgentspaceKitContext>) => provider.getCodexChatThreadRepository({ ...overrides, ...o }),
        getCodexChatMessageRepository: (o?: Partial<AgentspaceKitContext>) => provider.getCodexChatMessageRepository({ ...overrides, ...o }),
        getCodexChatSettingRepository: (o?: Partial<AgentspaceKitContext>) => provider.getCodexChatSettingRepository({ ...overrides, ...o }),
        getChatRoomRepository: (o?: Partial<AgentspaceKitContext>) => provider.getChatRoomRepository({ ...overrides, ...o }),
        getChatRoomMemberRepository: (o?: Partial<AgentspaceKitContext>) => provider.getChatRoomMemberRepository({ ...overrides, ...o }),
        getChatRoomBindingRepository: (o?: Partial<AgentspaceKitContext>) => provider.getChatRoomBindingRepository({ ...overrides, ...o }),
        getChatMessageRepository: (o?: Partial<AgentspaceKitContext>) => provider.getChatMessageRepository({ ...overrides, ...o }),
        getDiscussionTopicRepository: (o?: Partial<AgentspaceKitContext>) => provider.getDiscussionTopicRepository({ ...overrides, ...o }),
        getDiscussionTurnRepository: (o?: Partial<AgentspaceKitContext>) => provider.getDiscussionTurnRepository({ ...overrides, ...o }),
        getDiscussionOutputRepository: (o?: Partial<AgentspaceKitContext>) => provider.getDiscussionOutputRepository({ ...overrides, ...o }),
        getExperienceItemRepository: (o?: Partial<AgentspaceKitContext>) => provider.getExperienceItemRepository({ ...overrides, ...o }),
        getMemoryItemRepository: (o?: Partial<AgentspaceKitContext>) => provider.getMemoryItemRepository({ ...overrides, ...o }),
        getMissionRepository: (o?: Partial<AgentspaceKitContext>) => provider.getMissionRepository({ ...overrides, ...o }),
        getTagRepository: (o?: Partial<AgentspaceKitContext>) => provider.getTagRepository({ ...overrides, ...o }),
        getWorkflowDefinitionRepository: (o?: Partial<AgentspaceKitContext>) => provider.getWorkflowDefinitionRepository({ ...overrides, ...o }),
        getWorkflowInstanceRepository: (o?: Partial<AgentspaceKitContext>) => provider.getWorkflowInstanceRepository({ ...overrides, ...o }),
        getWorkflowStepRunRepository: (o?: Partial<AgentspaceKitContext>) => provider.getWorkflowStepRunRepository({ ...overrides, ...o }),
        getAll: (o?: Partial<AgentspaceKitContext>) => provider.getAll({ ...overrides, ...o }),
        createAll: (o?: Partial<AgentspaceKitContext>) => provider.createAll({ ...overrides, ...o }),
        clearServiceCache: (cacheKey?: string) => provider.clearServiceCache(cacheKey),
        clearAgentProfileServiceCache: (cacheKey?: string) => provider.clearAgentProfileServiceCache(cacheKey),
        clearProjectServiceCache: (cacheKey?: string) => provider.clearProjectServiceCache(cacheKey),
        clearProjectPathServiceCache: (cacheKey?: string) => provider.clearProjectPathServiceCache(cacheKey),
        clearProjectMemberServiceCache: (cacheKey?: string) => provider.clearProjectMemberServiceCache(cacheKey),
        clearPromptServiceCache: (cacheKey?: string) => provider.clearPromptServiceCache(cacheKey),
        clearPromptVersionServiceCache: (cacheKey?: string) => provider.clearPromptVersionServiceCache(cacheKey),
        clearResourceServiceCache: (cacheKey?: string) => provider.clearResourceServiceCache(cacheKey),
        clearSkillServiceCache: (cacheKey?: string) => provider.clearSkillServiceCache(cacheKey),
        clearSkillVersionServiceCache: (cacheKey?: string) => provider.clearSkillVersionServiceCache(cacheKey),
        clearKanbanBoardServiceCache: (cacheKey?: string) => provider.clearKanbanBoardServiceCache(cacheKey),
        clearKanbanColumnServiceCache: (cacheKey?: string) => provider.clearKanbanColumnServiceCache(cacheKey),
        clearSprintServiceCache: (cacheKey?: string) => provider.clearSprintServiceCache(cacheKey),
        clearSprintItemServiceCache: (cacheKey?: string) => provider.clearSprintItemServiceCache(cacheKey),
        clearTaskServiceCache: (cacheKey?: string) => provider.clearTaskServiceCache(cacheKey),
        clearTaskCommentServiceCache: (cacheKey?: string) => provider.clearTaskCommentServiceCache(cacheKey),
        clearAgentSessionServiceCache: (cacheKey?: string) => provider.clearAgentSessionServiceCache(cacheKey),
        clearAgentRunServiceCache: (cacheKey?: string) => provider.clearAgentRunServiceCache(cacheKey),
        clearAgentRunEventServiceCache: (cacheKey?: string) => provider.clearAgentRunEventServiceCache(cacheKey),
        clearActivityItemServiceCache: (cacheKey?: string) => provider.clearActivityItemServiceCache(cacheKey),
        clearArtifactServiceCache: (cacheKey?: string) => provider.clearArtifactServiceCache(cacheKey),
        clearArtifactLinkServiceCache: (cacheKey?: string) => provider.clearArtifactLinkServiceCache(cacheKey),
        clearCodexChatThreadServiceCache: (cacheKey?: string) => provider.clearCodexChatThreadServiceCache(cacheKey),
        clearCodexChatMessageServiceCache: (cacheKey?: string) => provider.clearCodexChatMessageServiceCache(cacheKey),
        clearCodexChatSettingServiceCache: (cacheKey?: string) => provider.clearCodexChatSettingServiceCache(cacheKey),
        clearChatServiceCache: (cacheKey?: string) => provider.clearChatServiceCache(cacheKey),
        clearDiscussionServiceCache: (cacheKey?: string) => provider.clearDiscussionServiceCache(cacheKey),
        clearExperienceItemServiceCache: (cacheKey?: string) => provider.clearExperienceItemServiceCache(cacheKey),
        clearMemoryItemServiceCache: (cacheKey?: string) => provider.clearMemoryItemServiceCache(cacheKey),
        clearMissionServiceCache: (cacheKey?: string) => provider.clearMissionServiceCache(cacheKey),
        clearTagServiceCache: (cacheKey?: string) => provider.clearTagServiceCache(cacheKey),
        clearWorkflowDefinitionServiceCache: (cacheKey?: string) => provider.clearWorkflowDefinitionServiceCache(cacheKey),
        clearWorkflowInstanceServiceCache: (cacheKey?: string) => provider.clearWorkflowInstanceServiceCache(cacheKey),
        clearWorkflowStepRunServiceCache: (cacheKey?: string) => provider.clearWorkflowStepRunServiceCache(cacheKey),
        reset: (opts?: { services?: boolean; repositories?: boolean }) => provider.reset(opts),
        getRegistryStats: () => provider.getRegistryStats(),
        resolveLogger: (o?: Partial<AgentspaceKitContext>) => provider.resolveLogger({ ...overrides, ...o }),
      }
    },
  }
}

export function buildAgentspaceKitStaticConfig(envConfig: AgentspaceKitEnvConfig): AgentspaceKitStaticConfig {
  const repoUrl = envConfig.repoUrl
  const repoType = inferRepoType(repoUrl)

  return {
    logLevel: envConfig.logLevel,
    agentProfileRepository: { repositoryType: repoType, url: repoUrl },
    projectRepository: { repositoryType: repoType, url: repoUrl },
    projectPathRepository: { repositoryType: repoType, url: repoUrl },
    scopeRepository: { repositoryType: repoType, url: repoUrl },
    projectMemberRepository: { repositoryType: repoType, url: repoUrl },
    promptRepository: { repositoryType: repoType, url: repoUrl },
    promptVersionRepository: { repositoryType: repoType, url: repoUrl },
    resourceRepository: { repositoryType: repoType, url: repoUrl },
    skillRepository: { repositoryType: repoType, url: repoUrl },
    skillVersionRepository: { repositoryType: repoType, url: repoUrl },
    kanbanBoardRepository: { repositoryType: repoType, url: repoUrl },
    kanbanColumnRepository: { repositoryType: repoType, url: repoUrl },
    sprintRepository: { repositoryType: repoType, url: repoUrl },
    sprintItemRepository: { repositoryType: repoType, url: repoUrl },
    taskRepository: { repositoryType: repoType, url: repoUrl },
    taskChecklistItemRepository: { repositoryType: repoType, url: repoUrl },
    taskCommentRepository: { repositoryType: repoType, url: repoUrl },
    taskLabelRepository: { repositoryType: repoType, url: repoUrl },
    taskLabelLinkRepository: { repositoryType: repoType, url: repoUrl },
    taskRelationRepository: { repositoryType: repoType, url: repoUrl },
    agentSessionRepository: { repositoryType: repoType, url: repoUrl },
    agentRunRepository: { repositoryType: repoType, url: repoUrl },
    agentRunEventRepository: { repositoryType: repoType, url: repoUrl },
    activityItemRepository: { repositoryType: repoType, url: repoUrl },
    artifactRepository: { repositoryType: repoType, url: repoUrl },
    artifactLinkRepository: { repositoryType: repoType, url: repoUrl },
    codexChatThreadRepository: { repositoryType: repoType, url: repoUrl },
    codexChatMessageRepository: { repositoryType: repoType, url: repoUrl },
    codexChatSettingRepository: { repositoryType: repoType, url: repoUrl },
    chatRoomRepository: { repositoryType: repoType, url: repoUrl },
    chatRoomMemberRepository: { repositoryType: repoType, url: repoUrl },
    chatRoomBindingRepository: { repositoryType: repoType, url: repoUrl },
    chatMessageRepository: { repositoryType: repoType, url: repoUrl },
    discussionTopicRepository: { repositoryType: repoType, url: repoUrl },
    discussionTurnRepository: { repositoryType: repoType, url: repoUrl },
    discussionOutputRepository: { repositoryType: repoType, url: repoUrl },
    experienceItemRepository: { repositoryType: repoType, url: repoUrl },
    memoryItemRepository: { repositoryType: repoType, url: repoUrl },
    missionRepository: { repositoryType: repoType, url: repoUrl },
    tagRepository: { repositoryType: repoType, url: repoUrl },
    workflowDefinitionRepository: { repositoryType: repoType, url: repoUrl },
    workflowInstanceRepository: { repositoryType: repoType, url: repoUrl },
    workflowStepRunRepository: { repositoryType: repoType, url: repoUrl },
  }
}

export type CreateAgentspaceKitWithEnvOptions = {
  name?: string
  envConfig: AgentspaceKitEnvConfig
  baseContext: {
    tenantId: string
    locale?: string
    fallbackLocale?: string
    logger?: XfLogger
  }
  getCacheKey?: (context: AgentspaceKitContext) => string | null
} & Pick<AgentspaceKitProviderOptions, 'cache' | 'metrics' | 'resilience' | 'transformService' | 'resolveLogger'>

export function createAgentspaceKitWithEnv(options: CreateAgentspaceKitWithEnvOptions) {
  const staticConfig = buildAgentspaceKitStaticConfig(options.envConfig)
  const envCfg = parseEnvConfig()

  const statsEnabled = envCfg.statsEnabled === true
  const counters = statsEnabled ? new CountersMetricsCollector() : undefined
  const loggerMetrics = statsEnabled ? new LoggerMetricsCollector(undefined) : undefined
  const metricsCollector =
    options.metrics ?? (counters && loggerMetrics ? new MultiMetricsCollector([counters, loggerMetrics]) : counters ?? loggerMetrics)

  const cacheMerged = (options.cache || envCfg.cacheGlobal)
    ? ({ ...(options.cache ?? {}), ...(envCfg.cacheGlobal ?? {}) } as AgentspaceKitProviderOptions['cache'])
    : undefined

  const resilienceMerged = (options.resilience || envCfg.resilience)
    ? ({ ...(options.resilience ?? {}), ...(envCfg.resilience ?? {}) })
    : undefined

  const kit = createAgentspaceKit({
    name: options.name ?? 'aops-kit',
    staticConfig,
    getContext: (overrides?: Partial<AgentspaceKitContext>) => ({
      tenantId: options.baseContext.tenantId,
      locale: options.baseContext.locale,
      fallbackLocale: options.baseContext.fallbackLocale,
      ...overrides,
      logger: overrides?.logger ?? options.baseContext.logger,
    }),
    resolveLogger: (ctx) => options.resolveLogger?.(ctx) ?? ctx.logger ?? options.baseContext.logger,
    getCacheKey: (ctx) => options.getCacheKey?.(ctx) ?? cacheKeyFromLocale(ctx.locale, ctx.fallbackLocale),
    cache: cacheMerged,
    metrics: metricsCollector,
    resilience: resilienceMerged as AgentspaceKitProviderOptions['resilience'],
    transformService: options.transformService,
  })

  return {
    kit,
    getMetricsSnapshot: () => (counters ? counters.snapshot() : null),
    validate: async () => {
      const svc = await kit.createAll()
      void svc
      return Effect.succeed(true)
    },
  }
}
