import fs from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'
import { Command } from 'commander'
import { banner, logError, logInfo, logSuccess, logWarn } from '@aopslab/xf-cli-ui'

import { findWorkspaceRoot } from '../utils/workspace-root.js'
import { promptConfirm, promptInput } from '../utils/prompts.js'
import { buildAopsRepoConfig } from '../utils/repo-config.js'

type InitOptions = {
  root?: string
  repoName?: string
  projectName?: string
  projectSlug?: string
  projectId?: string
  force?: boolean
  agentsMd?: boolean
  yes?: boolean
  json?: boolean
}

function nonEmpty(value: unknown): string | undefined {
  if (typeof value !== 'string') return undefined
  const normalized = value.trim()
  return normalized || undefined
}

async function readJsonFile(filePath: string): Promise<Record<string, unknown> | null> {
  try {
    return JSON.parse(await fs.readFile(filePath, 'utf8')) as Record<string, unknown>
  } catch {
    return null
  }
}

function communityInitSection(): string {
  return `#INIT

This section is generated by AOPS Community.

Server-first model:
- The local AOPS server is canonical for Projectman, Agentspace, and Docman writes.
- .aops/aops.config.json stores repo metadata; hosted mirror and planning views under .aops are read-only caches.
- Use aops-cli agent tools for capability discovery and aops-cli host health for readiness.
- ChatV3 runs self-hosted/local-trusted in this distribution.
`
}

async function writeCommunityAgentsSection(rootDir: string): Promise<void> {
  const filePath = path.join(rootDir, 'AGENTS.md')
  const section = `${communityInitSection().trimEnd()}\n\n`
  const current = existsSync(filePath) ? await fs.readFile(filePath, 'utf8') : ''
  const match = current.match(/^#\s*INIT\b.*$/im)
  let remainder = current
  if (match?.index !== undefined) {
    const afterHeader = match.index + match[0].length
    const nextHeader = current.slice(afterHeader).match(/^\s*#(?!\s*INIT\b)/m)
    const end = nextHeader?.index === undefined ? current.length : afterHeader + nextHeader.index
    remainder = `${current.slice(0, match.index)}${current.slice(end)}`
  }
  await fs.writeFile(filePath, `${section}${remainder.trimStart()}`.trimEnd() + '\n', 'utf8')
}

export async function runInit(options: InitOptions = {}): Promise<void> {
  const startDir = process.cwd()
  const rootDir = options.root ? path.resolve(startDir, options.root) : findWorkspaceRoot(startDir)
  const configPath = path.join(rootDir, '.aops', 'aops.config.json')
  const interactive = options.yes !== true && options.json !== true
  const existingConfig = existsSync(configPath) ? await readJsonFile(configPath) : null
  if (interactive) banner('AOPS Community Init')

  if (existsSync(configPath) && options.force !== true) {
    const overwrite = interactive
      ? await promptConfirm({ message: `${configPath} exists. Overwrite?`, default: false })
      : false
    if (!overwrite) {
      logError('aops.config.json already exists. Use --force to overwrite.')
      process.exitCode = 1
      return
    }
  }

  const existingRepoName = nonEmpty((existingConfig as any)?.repo?.name)
  let repoName = nonEmpty(options.repoName)
  const fallbackRepoName = path.basename(rootDir)
  if (!repoName && interactive) {
    repoName = nonEmpty(await promptInput({ message: 'Repository name:', default: existingRepoName ?? fallbackRepoName }))
  }
  repoName ??= existingRepoName ?? fallbackRepoName
  if (!repoName) {
    logError('Repository name is required.')
    process.exitCode = 1
    return
  }

  const existingProjectName = nonEmpty((existingConfig as any)?.activeProjectName)
    ?? nonEmpty((existingConfig as any)?.projects?.[0]?.name)
  const existingProjectSlug = nonEmpty((existingConfig as any)?.projects?.[0]?.slug)
  const existingProjectId = nonEmpty((existingConfig as any)?.projects?.[0]?.projectId)
  const projectName = nonEmpty(options.projectName) ?? existingProjectName ?? repoName
  const projectSlug = nonEmpty(options.projectSlug) ?? existingProjectSlug
  const projectId = nonEmpty(options.projectId) ?? existingProjectId ?? projectName
  const config = buildAopsRepoConfig({ repoName, projectName, projectSlug, projectId })
  await fs.mkdir(path.dirname(configPath), { recursive: true })
  await fs.writeFile(configPath, `${JSON.stringify(config, null, 2)}\n`, 'utf8')
  if (options.agentsMd !== false) {
    try {
      await writeCommunityAgentsSection(rootDir)
    } catch (error) {
      logWarn(`Failed to update AGENTS.md: ${error instanceof Error ? error.message : String(error)}`)
    }
  }

  if (options.json) {
    console.log(JSON.stringify(config, null, 2))
    return
  }
  logSuccess(`Created ${configPath}`)
  logInfo('Next: start the packaged AOPS Community runtime, then run `aops-cli host health`.')
}

export function makeInitCommand(): Command {
  const command = new Command('init').description('Initialize repo-local AOPS Community metadata (.aops)')
  command
    .option('--root <path>', 'Workspace root override')
    .option('--repo-name <name>', 'Repository display name')
    .option('--project-name <name>', 'Project name')
    .option('--project-slug <text>', 'Project slug to persist')
    .option('--project-id <id>', 'Project id')
    .option('--force', 'Overwrite existing aops.config.json')
    .option('--no-agents-md', 'Skip AGENTS.md #INIT update')
    .option('--yes', 'Use defaults and skip prompts')
    .option('--json', 'Output JSON only')
    .action(async (options: InitOptions) => runInit(options))
  return command
}
